openapi: 3.0.0

info:
  title: Prepaid Verification API
  description: API specifications for prepaid verification
  version: 1.0.0
  contact:
    name: R&D
    email: rdoffice@zen.com.my

servers:
  - url: prepaid-api-server
    description: Prepaid API server

paths:
  /listall:
    get:
      description: List all
      summary: Describe this route
      responses:
        200:
          description: Description
          content: 
            application/json:
              schema:
                type: string
  /verify:
    get:
      description: Get verification details based on Telco
      summary: Get verification details based on Telco
      parameters:
        - in: query
          name: telco
          required:  true
          description:  description
          schema:
            type:  string
            example: celcom
      responses:
        200:
          description: Description
          content: 
            application/json:
              schema:
                type: string
    post:
      description: Post verification list based on Telco
      summary: Post verification list based on Telco
      parameters:
        - in: query
          name: telco
          required:  true
          description:  Telco short name
          schema:
            type:  string
            example: celcom
        - in: query
          name: batch
          description: Batch name
          required: false
          schema:
            type: string
        - in: query
          name: attachment
          description: description
          required: false
          schema:
            type: string
            format: binary

      responses:
        200:
          description: Description
          content: 
            application/json:
              schema:
                type: string
        